### ISSUE TITLE
Civic not working with ToshiAPP

### ISSUE THREAD

**Issue by devbold** [blockvis/civic-sip-php#5]
### Currently Civic is not working with the Toshi app, 
**Toshi does not handle the Civic Intent and it gets stuck on an invalid URL scheme error.** 

![42241423-c8c179ec-7f0a-11e8-9097-2c175807b21a](https://user-images.githubusercontent.com/12101846/42395370-0e169fe2-8134-11e8-8165-2009e0b41f48.png)

**Comment by cheelahim** [comment]
Hello @ignacioperezroca. Honestly I'm not sure why you opened the issue with us. 
If I understand correctly Toshi is a mobile application. How is it related to Civic PHP client? Have you tried to contact Civic App support?

**Comment by devbold** [comment]
Sory @cheelahim, this is not the github of Civic app?
Thanks

**Comment by cheelahim** [comment]
@ignacioperezroca you're right, this is not the mobile app repo. We're providing PHP implementation of the Civic SIP client, which allows PHP web projects to integrate Civic login into their solutions. If you're having issues with mobile app you may want to contact Civic support team by sending an email to support@civic.com. But please provide as many details as you can, with screenshots and device information, so that they could get the right people onto this issue.
